# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo
  - file_length
  - type_body_length

# Exluded files
excluded:
  - Pods

# Customised rules
identifier_name:
  min_length:
    warning: 1
    error: 1
force_cast: warning
function_body_length: 200
force_try:
  severity: warning
line_length: 80

